version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: talentstream_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: talentstream_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: dev_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  pgdata:

# DATABASE_URL="postgres://postgres:password123@localhost:5432/talentstream_db"